import { useState } from 'react';
import { CalendarPlus, X } from 'lucide-react';

export type BookingDraft = { full_name: string; phone: string; email?: string; vehicle_summary: string; service_requested: string; preferred_date?: string; concern: string };

export function BookingComposer({ busy, onCreate }: { busy: boolean; onCreate: (draft: BookingDraft) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState<BookingDraft>({ full_name: '', phone: '', email: '', vehicle_summary: '', service_requested: '', preferred_date: '', concern: '' });
  async function submit(event: React.FormEvent) { event.preventDefault(); await onCreate(draft); setOpen(false); setDraft({ full_name: '', phone: '', email: '', vehicle_summary: '', service_requested: '', preferred_date: '', concern: '' }); }
  return <><button className="role-primary" type="button" onClick={() => setOpen(true)}><CalendarPlus /> Nueva cita</button>{open && <div className="ot-detail-backdrop"><section className="booking-composer" role="dialog" aria-modal="true" aria-label="Crear cita desde Kanban"><header><div><small>RECEPCIÓN</small><h2>Nueva cita del taller</h2><p>Quedará confirmada y visible en la agenda.</p></div><button aria-label="Cerrar" onClick={() => setOpen(false)}><X /></button></header><form onSubmit={submit}><label>Cliente<input required minLength={3} value={draft.full_name} onChange={(e) => setDraft({ ...draft, full_name: e.target.value })} /></label><label>Teléfono<input required minLength={7} value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} /></label><label>Correo<input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} /></label><label>Vehículo / VIN<input required minLength={3} value={draft.vehicle_summary} onChange={(e) => setDraft({ ...draft, vehicle_summary: e.target.value })} /></label><label>Servicio<input required minLength={2} value={draft.service_requested} onChange={(e) => setDraft({ ...draft, service_requested: e.target.value })} /></label><label>Fecha y hora<input type="datetime-local" value={draft.preferred_date} onChange={(e) => setDraft({ ...draft, preferred_date: e.target.value })} /></label><label className="wide">Motivo<textarea required minLength={8} value={draft.concern} onChange={(e) => setDraft({ ...draft, concern: e.target.value })} /></label><button className="role-primary wide" disabled={busy}><CalendarPlus /> Confirmar y guardar cita</button></form></section></div>}</>;
}
