import { useCallback, useEffect, useState } from 'react';
import { BadgeDollarSign, BriefcaseBusiness, CheckCircle2, Clock3, Container, FileInput, MessageCircle, Plus, ShieldCheck, Truck, UsersRound } from 'lucide-react';
import {
  createAttendance, createEmployeeContract, createImportCase, createLeaveRequest, createPayrollRun,
  createPurchaseOrder, createSocialChannel, createSocialConversation, createSocialMessage, createSupplier,
  createUsedVehicle, getEnterpriseOverview, updateImportCaseStatus, updateLeaveRequestStatus,
  updatePayrollRunStatus, updatePurchaseOrderStatus, updateUsedVehicleStatus,
} from '../lib/api';
import type { EnterpriseOverview } from '../types';
import { ProcurementModule } from './ProcurementHrWorkspace';
import { HumanResourcesWorkspace } from './HumanResourcesWorkspace';

export type EnterpriseMode = 'PROCUREMENT' | 'HR' | 'USED' | 'SOCIAL';
const empty: EnterpriseOverview = { counts: {}, suppliers: [], purchase_orders: [], import_cases: [], contracts: [], attendance: [], leave_requests: [], payroll_runs: [], used_vehicles: [], social_channels: [], social_conversations: [] };
const money = (value: string | number, currency = 'HNL') => new Intl.NumberFormat('es-HN', { style: 'currency', currency }).format(Number(value));

export function EnterpriseWorkspace({ token, mode }: { token: string; mode: EnterpriseMode }) {
  const [data, setData] = useState<EnterpriseOverview>(empty);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setBusy(true); try { setData(await getEnterpriseOverview(token)); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar el módulo.'); } finally { setBusy(false); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function execute(action: () => Promise<unknown>, message: string) { setBusy(true); setError(''); try { await action(); setNotice(message); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo completar la operación.'); } finally { setBusy(false); } }
  return <div className="enterprise-workspace">
    {error && <p className="global-error">{error}</p>}{notice && <p className="enterprise-notice"><CheckCircle2 /> {notice}<button onClick={() => setNotice('')}>Cerrar</button></p>}
    {mode === 'PROCUREMENT' && <ProcurementModule data={data} busy={busy} execute={execute} />}
    {mode === 'HR' && <HumanResourcesWorkspace token={token} data={data} busy={busy} execute={execute} />}
    {mode === 'USED' && <UsedVehicles token={token} data={data} busy={busy} execute={execute} />}
    {mode === 'SOCIAL' && <SocialInbox token={token} data={data} busy={busy} execute={execute} />}
  </div>;
}

type Exec = (action: () => Promise<unknown>, message: string) => Promise<void>;

function Procurement({ token, data, busy, execute }: { token: string; data: EnterpriseOverview; busy: boolean; execute: Exec }) {
  const [supplier, setSupplier] = useState({ code: '', name: '', tax_id: '', email: '', phone: '', payment_terms_days: 30, currency: 'HNL' });
  const [order, setOrder] = useState({ supplier_id: '', currency: 'HNL', expected_at: '', notes: '', sku: '', description: '', quantity: '1', unit_cost: '0' });
  const [shipment, setShipment] = useState({ purchase_order_id: '', incoterm: 'CIF', origin_country: 'US', destination_port: 'Puerto Cortés', eta: '', allocation_method: 'BY_VALUE', kind: 'FREIGHT', description: 'Flete internacional', amount: '0', currency: 'USD' });
  const purchaseNext: Record<string, string | undefined> = { DRAFT: 'SUBMITTED', SUBMITTED: 'APPROVED', APPROVED: 'RECEIVED', PARTIALLY_RECEIVED: 'RECEIVED', RECEIVED: 'CLOSED' };
  const importNext: Record<string, string | undefined> = { PLANNED: 'IN_TRANSIT', IN_TRANSIT: 'CUSTOMS', CUSTOMS: 'RECEIVED', RECEIVED: 'ALLOCATED' };
  return <><header className="content-header"><div><span>Abastecimiento</span><h1>Compras, proveedores e importaciones</h1><p>Solicitud → aprobación → orden ERP → recepción → costo puesto en bodega. No crea cuentas por pagar locales.</p></div><b className="enterprise-sync"><ShieldCheck /> ERPNext autoritativo</b></header>
    <div className="enterprise-kpis"><article><UsersRound /><span><small>Proveedores</small><b>{data.counts.suppliers ?? 0}</b></span></article><article><FileInput /><span><small>Órdenes</small><b>{data.counts.purchase_orders ?? 0}</b></span></article><article><Container /><span><small>Importaciones</small><b>{data.counts.import_cases ?? 0}</b></span></article><article><Clock3 /><span><small>ERP pendientes</small><b>{data.purchase_orders.filter((item) => item.erp_sync_status === 'PENDING').length}</b></span></article></div>
    <div className="enterprise-forms"><form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createSupplier('__cookie_session__', supplier), 'Proveedor creado y enviado a sincronización ERP.'); }}><h2><Plus /> Nuevo proveedor</h2><label>Código<input required value={supplier.code} onChange={(event) => setSupplier({ ...supplier, code: event.target.value })} /></label><label>Nombre legal<input required value={supplier.name} onChange={(event) => setSupplier({ ...supplier, name: event.target.value })} /></label><label>RTN<input value={supplier.tax_id} onChange={(event) => setSupplier({ ...supplier, tax_id: event.target.value })} /></label><label>Correo<input type="email" value={supplier.email} onChange={(event) => setSupplier({ ...supplier, email: event.target.value })} /></label><button disabled={busy}>Guardar proveedor</button></form>
      <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createPurchaseOrder('__cookie_session__', { supplier_id: order.supplier_id, currency: order.currency, expected_at: order.expected_at || undefined, notes: order.notes, items: [{ sku: order.sku, description: order.description, quantity: order.quantity, unit_cost: order.unit_cost }] }), 'Orden de compra creada en borrador.'); }}><h2><BriefcaseBusiness /> Nueva orden</h2><label>Proveedor<select required value={order.supplier_id} onChange={(event) => setOrder({ ...order, supplier_id: event.target.value })}><option value="">Seleccione</option>{data.suppliers.map((item) => <option value={item.id} key={item.id}>{item.code} · {item.name}</option>)}</select></label><label>SKU<input required value={order.sku} onChange={(event) => setOrder({ ...order, sku: event.target.value })} /></label><label>Descripción<input required value={order.description} onChange={(event) => setOrder({ ...order, description: event.target.value })} /></label><div><label>Cantidad<input type="number" min="0.001" step="0.001" required value={order.quantity} onChange={(event) => setOrder({ ...order, quantity: event.target.value })} /></label><label>Costo unitario<input type="number" min="0" step="0.01" required value={order.unit_cost} onChange={(event) => setOrder({ ...order, unit_cost: event.target.value })} /></label></div><button disabled={busy}>Crear orden</button></form>
      <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createImportCase('__cookie_session__', { purchase_order_id: shipment.purchase_order_id, incoterm: shipment.incoterm, origin_country: shipment.origin_country, destination_port: shipment.destination_port, eta: shipment.eta || undefined, allocation_method: shipment.allocation_method, costs: [{ kind: shipment.kind, description: shipment.description, amount: shipment.amount, currency: shipment.currency }] }), 'Expediente de importación creado.'); }}><h2><Container /> Nueva importación</h2><label>Orden de compra<select required value={shipment.purchase_order_id} onChange={(event) => setShipment({ ...shipment, purchase_order_id: event.target.value })}><option value="">Seleccione</option>{data.purchase_orders.map((item) => <option value={item.id} key={item.id}>{item.number} · {money(item.total, item.currency)}</option>)}</select></label><div><label>Incoterm<select value={shipment.incoterm} onChange={(event) => setShipment({ ...shipment, incoterm: event.target.value })}><option>CIF</option><option>FOB</option><option>EXW</option><option>DDP</option></select></label><label>ETA<input type="date" value={shipment.eta} onChange={(event) => setShipment({ ...shipment, eta: event.target.value })} /></label></div><label>Costo adicional<input type="number" min="0" step="0.01" value={shipment.amount} onChange={(event) => setShipment({ ...shipment, amount: event.target.value })} /></label><button disabled={busy}>Abrir expediente</button></form></div>
    <section className="enterprise-board"><div className="role-panel"><h2>Órdenes de compra</h2>{data.purchase_orders.map((item) => <article key={item.id}><header><b>{item.number}</b><em>{item.status}</em></header><p>{data.suppliers.find((row) => row.id === item.supplier_id)?.name ?? 'Proveedor'} · {money(item.total, item.currency)}</p><small>ERP {item.erp_sync_status}{item.erpnext_purchase_order_id ? ` · ${item.erpnext_purchase_order_id}` : ''}</small>{purchaseNext[item.status] && <button disabled={busy} onClick={() => void execute(() => updatePurchaseOrderStatus('__cookie_session__', item.id, purchaseNext[item.status]!), `Orden movida a ${purchaseNext[item.status]}.`)}>Mover a {purchaseNext[item.status]}</button>}</article>)}</div><div className="role-panel"><h2>Importaciones y costos</h2>{data.import_cases.map((item) => <article key={item.id}><header><b>{item.number}</b><em>{item.status}</em></header><p>{item.incoterm} · {item.origin_country} → {item.destination_port}</p><small>Adicional {money(item.additional_cost_total)} · costo ERP {item.landed_cost_status}</small>{importNext[item.status] && <button disabled={busy} onClick={() => void execute(() => updateImportCaseStatus('__cookie_session__', item.id, importNext[item.status]!), `Importación movida a ${importNext[item.status]}.`)}>Mover a {importNext[item.status]}</button>}</article>)}</div></section></>;
}

function HumanResources({ token, data, busy, execute }: { token: string; data: EnterpriseOverview; busy: boolean; execute: Exec }) {
  const [contract, setContract] = useState({ employee_code: '', employee_name: '', date_of_birth: '', job_title: 'Técnico', contract_type: 'PERMANENT', start_date: '', monthly_salary: '0', standard_hours_weekly: '44', currency: 'HNL' });
  const [attendance, setAttendance] = useState({ contract_id: '', work_date: '', regular_hours: '8', overtime_hours: '0' });
  const [leave, setLeave] = useState({ contract_id: '', leave_type: 'VACATION', start_date: '', end_date: '', reason: '' });
  const [period, setPeriod] = useState({ period_start: '', period_end: '' });
  return <><header className="content-header"><div><span>Personas</span><h1>RR. HH., asistencia y nómina</h1><p>Contratos, jornadas, horas extra, permisos y preparación de nómina. El asiento y pago sólo existen cuando ERP/HRMS confirma.</p></div></header><div className="enterprise-kpis"><article><UsersRound /><span><small>Contratos activos</small><b>{data.contracts.filter((item) => item.status === 'ACTIVE').length}</b></span></article><article><Clock3 /><span><small>Marcaciones</small><b>{data.attendance.length}</b></span></article><article><FileInput /><span><small>Permisos pendientes</small><b>{data.leave_requests.filter((item) => item.status === 'PENDING').length}</b></span></article><article><BadgeDollarSign /><span><small>Nóminas</small><b>{data.payroll_runs.length}</b></span></article></div>
    <div className="enterprise-forms enterprise-forms--four"><form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createEmployeeContract('__cookie_session__', contract), 'Contrato registrado y empleado enviado a ERP.'); }}><h2><Plus /> Contrato</h2><label>Código<input required value={contract.employee_code} onChange={(event) => setContract({ ...contract, employee_code: event.target.value })} /></label><label>Empleado<input required value={contract.employee_name} onChange={(event) => setContract({ ...contract, employee_name: event.target.value })} /></label><label>Fecha de nacimiento<input required type="date" value={contract.date_of_birth} onChange={(event) => setContract({ ...contract, date_of_birth: event.target.value })} /></label><label>Cargo<input required value={contract.job_title} onChange={(event) => setContract({ ...contract, job_title: event.target.value })} /></label><label>Inicio<input required type="date" value={contract.start_date} onChange={(event) => setContract({ ...contract, start_date: event.target.value })} /></label><label>Salario mensual<input required type="number" min="0.01" value={contract.monthly_salary} onChange={(event) => setContract({ ...contract, monthly_salary: event.target.value })} /></label><button disabled={busy}>Crear contrato</button></form>
    <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createAttendance('__cookie_session__', attendance), 'Asistencia y horas registradas.'); }}><h2><Clock3 /> Asistencia</h2><ContractSelect value={attendance.contract_id} data={data} onChange={(contract_id) => setAttendance({ ...attendance, contract_id })} /><label>Fecha<input required type="date" value={attendance.work_date} onChange={(event) => setAttendance({ ...attendance, work_date: event.target.value })} /></label><div><label>Regulares<input type="number" min="0" max="24" step="0.25" value={attendance.regular_hours} onChange={(event) => setAttendance({ ...attendance, regular_hours: event.target.value })} /></label><label>Extra<input type="number" min="0" max="16" step="0.25" value={attendance.overtime_hours} onChange={(event) => setAttendance({ ...attendance, overtime_hours: event.target.value })} /></label></div><button disabled={busy}>Registrar jornada</button></form>
    <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createLeaveRequest('__cookie_session__', leave), 'Solicitud de permiso creada.'); }}><h2><FileInput /> Permiso</h2><ContractSelect value={leave.contract_id} data={data} onChange={(contract_id) => setLeave({ ...leave, contract_id })} /><label>Tipo<select value={leave.leave_type} onChange={(event) => setLeave({ ...leave, leave_type: event.target.value })}><option value="VACATION">Vacaciones</option><option value="SICK">Incapacidad</option><option value="PERSONAL">Personal</option><option value="UNPAID">Sin goce</option></select></label><div><label>Desde<input required type="date" value={leave.start_date} onChange={(event) => setLeave({ ...leave, start_date: event.target.value })} /></label><label>Hasta<input required type="date" value={leave.end_date} onChange={(event) => setLeave({ ...leave, end_date: event.target.value })} /></label></div><button disabled={busy}>Solicitar</button></form>
    <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createPayrollRun('__cookie_session__', { ...period, contract_ids: data.contracts.filter((item) => item.status === 'ACTIVE').map((item) => item.id) }), 'Borrador de nómina calculado.'); }}><h2><BadgeDollarSign /> Calcular nómina</h2><label>Inicio<input required type="date" value={period.period_start} onChange={(event) => setPeriod({ ...period, period_start: event.target.value })} /></label><label>Final<input required type="date" value={period.period_end} onChange={(event) => setPeriod({ ...period, period_end: event.target.value })} /></label><p>Incluye salario mensual y horas extra al 150 %. Deducciones legales deben configurarse con el contador en HRMS.</p><button disabled={busy || !data.contracts.length}>Crear borrador</button></form></div>
    <section className="enterprise-board"><div className="role-panel"><h2>Permisos por aprobar</h2>{data.leave_requests.map((item) => <article key={item.id}><header><b>{data.contracts.find((row) => row.id === item.contract_id)?.employee_name}</b><em>{item.status}</em></header><p>{item.leave_type} · {item.start_date} → {item.end_date}</p>{item.status === 'PENDING' && <footer><button onClick={() => void execute(() => updateLeaveRequestStatus('__cookie_session__', item.id, 'APPROVED'), 'Permiso aprobado.')}>Aprobar</button><button onClick={() => void execute(() => updateLeaveRequestStatus('__cookie_session__', item.id, 'REJECTED'), 'Permiso rechazado.')}>Rechazar</button></footer>}</article>)}</div><div className="role-panel"><h2>Nóminas y conciliación</h2>{data.payroll_runs.map((item) => <article key={item.id}><header><b>{item.number}</b><em>{item.status}</em></header><p>{item.period_start} → {item.period_end} · neto {money(item.net_total)}</p><small>ERP {item.erp_sync_status}{item.erpnext_payroll_entry_id ? ` · ${item.erpnext_payroll_entry_id}` : ''}</small>{item.status === 'DRAFT' && <button onClick={() => void execute(() => updatePayrollRunStatus('__cookie_session__', item.id, 'REVIEWED'), 'Nómina revisada.')}>Marcar revisada</button>}{item.status === 'REVIEWED' && <button onClick={() => void execute(() => updatePayrollRunStatus('__cookie_session__', item.id, 'APPROVED'), 'Nómina aprobada y enviada a HRMS.')}>Aprobar y enviar ERP</button>}</article>)}</div></section></>;
}

function ContractSelect({ value, data, onChange }: { value: string; data: EnterpriseOverview; onChange: (value: string) => void }) { return <label>Empleado<select required value={value} onChange={(event) => onChange(event.target.value)}><option value="">Seleccione</option>{data.contracts.map((item) => <option value={item.id} key={item.id}>{item.employee_code} · {item.employee_name}</option>)}</select></label>; }

function UsedVehicles({ token, data, busy, execute }: { token: string; data: EnterpriseOverview; busy: boolean; execute: Exec }) {
  const [draft, setDraft] = useState({ vin: '', make: '', model: '', model_year: 2020, mileage_km: 0, acquisition_type: 'CONSIGNMENT', acquisition_cost: '0', reconditioning_cost: '0', target_sale_price: '0', owner_name: '' });
  const next: Record<string, string | undefined> = { APPRAISAL: 'ACQUIRED', ACQUIRED: 'RECONDITIONING', RECONDITIONING: 'READY', READY: 'PUBLISHED', PUBLISHED: 'RESERVED', RESERVED: 'SOLD' };
  return <><header className="content-header"><div><span>Nueva línea de negocio</span><h1>Compra, consignación y venta de usados</h1><p>Tasación → adquisición → reacondicionamiento → publicación → reserva → venta. El VIN evita duplicados.</p></div></header><div className="enterprise-layout"><form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createUsedVehicle('__cookie_session__', draft), 'Vehículo ingresado a tasación.'); }}><h2><Plus /> Ingresar unidad</h2><label>VIN<input required minLength={11} value={draft.vin} onChange={(event) => setDraft({ ...draft, vin: event.target.value })} /></label><div><label>Marca<input required value={draft.make} onChange={(event) => setDraft({ ...draft, make: event.target.value })} /></label><label>Modelo<input required value={draft.model} onChange={(event) => setDraft({ ...draft, model: event.target.value })} /></label></div><div><label>Año<input type="number" min="1900" max="2100" value={draft.model_year} onChange={(event) => setDraft({ ...draft, model_year: Number(event.target.value) })} /></label><label>Kilometraje<input type="number" min="0" value={draft.mileage_km} onChange={(event) => setDraft({ ...draft, mileage_km: Number(event.target.value) })} /></label></div><label>Modalidad<select value={draft.acquisition_type} onChange={(event) => setDraft({ ...draft, acquisition_type: event.target.value })}><option value="PURCHASE">Compra</option><option value="CONSIGNMENT">Consignación</option><option value="TRADE_IN">Recibido a cuenta</option></select></label><div><label>Costo/valor base<input type="number" min="0" value={draft.acquisition_cost} onChange={(event) => setDraft({ ...draft, acquisition_cost: event.target.value })} /></label><label>Precio objetivo<input type="number" min="0.01" value={draft.target_sale_price} onChange={(event) => setDraft({ ...draft, target_sale_price: event.target.value })} /></label></div><button disabled={busy}>Crear tasación</button></form><section className="used-board">{data.used_vehicles.map((item) => <article className="role-panel" key={item.id}><div className="used-photo"><Truck /></div><header><span><small>{item.vin}</small><h2>{item.make} {item.model} {item.model_year}</h2></span><em>{item.status}</em></header><dl><div><dt>Modalidad</dt><dd>{item.acquisition_type}</dd></div><div><dt>Inversión</dt><dd>{money(Number(item.acquisition_cost) + Number(item.reconditioning_cost))}</dd></div><div><dt>Precio objetivo</dt><dd>{money(item.target_sale_price)}</dd></div><div><dt>Margen previsto</dt><dd>{money(Number(item.target_sale_price) - Number(item.acquisition_cost) - Number(item.reconditioning_cost))}</dd></div></dl>{next[item.status] && <button disabled={busy} onClick={() => void execute(() => updateUsedVehicleStatus('__cookie_session__', item.id, next[item.status]!), `Vehículo movido a ${next[item.status]}.`)}>Mover a {next[item.status]}</button>}</article>)}</section></div></>;
}

function SocialInbox({ token, data, busy, execute }: { token: string; data: EnterpriseOverview; busy: boolean; execute: Exec }) {
  const [channel, setChannel] = useState({ channel_type: 'WHATSAPP', name: '', external_account_id: '', credential_reference: 'secret://social/' });
  const [conversation, setConversation] = useState({ channel_id: '', contact_name: '', contact_handle: '', consent_status: 'OPTED_IN', subject: '' });
  const [reply, setReply] = useState({ conversation_id: '', body: '', human_approved: true });
  return <><header className="content-header"><div><span>Atención omnicanal</span><h1>Hub Social con control humano</h1><p>Bandeja unificada, consentimiento, asignación y respuestas auditadas. Las credenciales quedan en el gestor de secretos, nunca en esta base.</p></div><b className="enterprise-sync"><ShieldCheck /> Salidas con aprobación</b></header><div className="enterprise-forms"><form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createSocialChannel('__cookie_session__', channel), 'Canal registrado. Falta validar su webhook con el proveedor.'); }}><h2><Plus /> Registrar canal</h2><label>Tipo<select value={channel.channel_type} onChange={(event) => setChannel({ ...channel, channel_type: event.target.value })}><option>WHATSAPP</option><option>FACEBOOK</option><option>INSTAGRAM</option><option>EMAIL</option><option>WEBCHAT</option></select></label><label>Nombre<input required value={channel.name} onChange={(event) => setChannel({ ...channel, name: event.target.value })} /></label><label>ID de cuenta<input required value={channel.external_account_id} onChange={(event) => setChannel({ ...channel, external_account_id: event.target.value })} /></label><label>Referencia de secreto<input required value={channel.credential_reference} onChange={(event) => setChannel({ ...channel, credential_reference: event.target.value })} /></label><button disabled={busy}>Registrar canal</button></form>
    <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createSocialConversation('__cookie_session__', conversation), 'Conversación creada y lista para asignar.'); }}><h2><MessageCircle /> Nueva conversación</h2><label>Canal<select required value={conversation.channel_id} onChange={(event) => setConversation({ ...conversation, channel_id: event.target.value })}><option value="">Seleccione</option>{data.social_channels.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.webhook_status}</option>)}</select></label><label>Contacto<input required value={conversation.contact_name} onChange={(event) => setConversation({ ...conversation, contact_name: event.target.value })} /></label><label>Teléfono/usuario<input required value={conversation.contact_handle} onChange={(event) => setConversation({ ...conversation, contact_handle: event.target.value })} /></label><label>Interés<input value={conversation.subject} onChange={(event) => setConversation({ ...conversation, subject: event.target.value })} /></label><button disabled={busy}>Abrir conversación</button></form>
    <form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void execute(() => createSocialMessage('__cookie_session__', reply.conversation_id, { direction: 'OUTBOUND', body: reply.body, human_approved: reply.human_approved }), 'Respuesta aprobada y puesta en cola.'); }}><h2><MessageCircle /> Responder</h2><label>Conversación<select required value={reply.conversation_id} onChange={(event) => setReply({ ...reply, conversation_id: event.target.value })}><option value="">Seleccione</option>{data.social_conversations.map((item) => <option value={item.id} key={item.id}>{item.contact_name} · {item.subject}</option>)}</select></label><label>Mensaje<textarea required rows={5} value={reply.body} onChange={(event) => setReply({ ...reply, body: event.target.value })} /></label><label className="enterprise-check"><input type="checkbox" checked={reply.human_approved} onChange={(event) => setReply({ ...reply, human_approved: event.target.checked })} /> Confirmo que una persona revisó esta respuesta.</label><button disabled={busy}>Aprobar y encolar</button></form></div><section className="social-inbox role-panel"><h2>Bandeja</h2>{data.social_conversations.map((item) => <article key={item.id}><MessageCircle /><span><strong>{item.contact_name}</strong><small>{item.contact_handle} · {item.subject || 'Sin asunto'}</small></span><em>{item.consent_status}</em><b>{item.status}</b></article>)}</section></>;
}
