import { useEffect, useState } from 'react';
import { BadgeDollarSign, Camera, Clock3, FileInput, PackageSearch, ShieldCheck, Wrench } from 'lucide-react';
import { COOKIE_SESSION, employeePunch, getEmployeeSelfService, requestOwnLeave } from '../lib/api';
import type { BoardResponse, EmployeeSelfService, StaffUser, WorkOrderCard } from '../types';

export function TechnicianWorkspace({ board, user, onOpen }: { board: BoardResponse; user: StaffUser | null; onOpen: (workOrder: WorkOrderCard) => void }) {
  const [tab, setTab] = useState<'WORK' | 'TIME' | 'LEAVE' | 'VOUCHERS'>('WORK');
  const [selfService, setSelfService] = useState<EmployeeSelfService | null>(null);
  const [message, setMessage] = useState('');
  const [leave, setLeave] = useState({ leave_type: 'PERSONAL', start_date: '', end_date: '', reason: '' });
  async function reloadSelfService() { try { setSelfService(await getEmployeeSelfService(COOKIE_SESSION)); setMessage(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cargar Mi RR. HH.'); } }
  useEffect(() => { if (user?.role === 'TECHNICIAN') void reloadSelfService(); }, [user?.id]);
  const all = board.columns.flatMap((column) => column.cards);
  const assigned = user?.role === 'TECHNICIAN' ? all.filter((item) => !item.technician_name || item.technician_name === user.full_name) : all;
  const waitingParts = assigned.filter((item) => (item.parts_required ?? []).some((part) => !['DELIVERED', 'RECEIVED'].includes(part.status))).length;
  const evidence = assigned.reduce((total, item) => total + (item.events ?? []).filter((event) => event.event_type === 'DIAGNOSTIC_EVIDENCE_ADDED').length, 0);
  return <div className="technician-workspace role-view">
    <header className="content-header"><div><span>Portal del mecánico</span><h1>Mi trabajo técnico</h1><p>Abra una OT para documentar diagnóstico, tiempos, fotografías, piezas y control de calidad desde una sola vista.</p></div><span className="erp-engine-status"><ShieldCheck /> Sesión: {user?.full_name ?? 'Supervisor'}</span></header>
    <div className="technician-kpis"><article><Wrench /><span><b>{assigned.length}</b><small>OT visibles</small></span></article><article><PackageSearch /><span><b>{waitingParts}</b><small>esperando piezas</small></span></article><article><Camera /><span><b>{evidence}</b><small>evidencias cargadas</small></span></article><article><Clock3 /><span><b>{assigned.filter((item) => !['READY_TO_INVOICE', 'INVOICED'].includes(item.status)).length}</b><small>trabajos activos</small></span></article></div>
    <nav className="enterprise-tabs technician-tabs" aria-label="Mi trabajo y recursos humanos"><button className={tab === 'WORK' ? 'active' : ''} onClick={() => setTab('WORK')}>Mis órdenes</button><button className={tab === 'TIME' ? 'active' : ''} onClick={() => setTab('TIME')}>Marcar entrada/salida</button><button className={tab === 'LEAVE' ? 'active' : ''} onClick={() => setTab('LEAVE')}>Mis permisos</button><button className={tab === 'VOUCHERS' ? 'active' : ''} onClick={() => setTab('VOUCHERS')}>Mis vouchers</button></nav>
    {message && <p className="document-message" role="alert">{message}</p>}
    {selfService && !selfService.linked && <section className="role-panel employee-link-warning" role="status"><ShieldCheck /><div><h2>Perfil pendiente de vinculación</h2><p>RR. HH. debe vincular este usuario a un contrato activo antes de habilitar marcación, permisos y vouchers. Las órdenes técnicas continúan disponibles.</p></div></section>}
    {tab === 'WORK' && <section className="technician-board">{assigned.map((workOrder) => { const pending = (workOrder.parts_required ?? []).filter((part) => !['DELIVERED', 'RECEIVED'].includes(part.status)).length; const photos = (workOrder.events ?? []).filter((event) => event.event_type === 'DIAGNOSTIC_EVIDENCE_ADDED').length; return <article key={workOrder.id}><header><span><small>{workOrder.external_reference}</small><h2>{workOrder.vehicle_label}</h2></span><b>{workOrder.status.replaceAll('_', ' ')}</b></header><h3>{workOrder.title}</h3><p>{workOrder.concern || 'Revise síntomas y orden de recepción.'}</p><dl><div><dt>Cliente</dt><dd>{workOrder.customer_name}</dd></div><div><dt>Bahía</dt><dd>{workOrder.bay_code || 'Por asignar'}</dd></div><div><dt>Fotos</dt><dd>{photos}</dd></div><div><dt>Piezas pendientes</dt><dd>{pending}</dd></div></dl><button onClick={() => onOpen(workOrder)}><Wrench /> Abrir OT y continuar</button></article>; })}{!assigned.length && <div className="empty-bookings">No hay órdenes asignadas a esta sesión.</div>}</section>}
    {tab === 'TIME' && <section className="role-panel employee-self-card"><Clock3 /><div><span>Jornada de hoy</span><h2>{selfService?.today_attendance?.check_in_at ? `Entrada ${new Date(selfService.today_attendance.check_in_at).toLocaleTimeString('es-HN')}` : 'Aún no ha marcado entrada'}</h2><p>{selfService?.today_attendance?.check_out_at ? `Salida ${new Date(selfService.today_attendance.check_out_at).toLocaleTimeString('es-HN')} · ${selfService.today_attendance.regular_hours} h regulares` : 'La salida calculará horas regulares y enviará el exceso a aprobación.'}</p></div><button disabled={!selfService?.linked || Boolean(selfService?.today_attendance?.check_in_at)} onClick={() => void employeePunch(COOKIE_SESSION, 'CHECK_IN').then(reloadSelfService)}>Marcar entrada</button><button disabled={!selfService?.linked || !selfService?.today_attendance?.check_in_at || Boolean(selfService?.today_attendance?.check_out_at)} onClick={() => void employeePunch(COOKIE_SESSION, 'CHECK_OUT').then(reloadSelfService)}>Marcar salida</button></section>}
    {tab === 'LEAVE' && <div className="enterprise-layout"><form className="role-panel enterprise-form" onSubmit={(event) => { event.preventDefault(); void requestOwnLeave(COOKIE_SESSION, leave).then(reloadSelfService); }}><h2><FileInput /> Solicitar permiso</h2><label>Tipo<select value={leave.leave_type} onChange={(event) => setLeave({ ...leave, leave_type: event.target.value })}><option value="VACATION">Vacaciones</option><option value="SICK">Incapacidad</option><option value="PERSONAL">Personal</option><option value="UNPAID">Sin goce</option></select></label><div><label>Desde<input required type="date" value={leave.start_date} onChange={(event) => setLeave({ ...leave, start_date: event.target.value })} /></label><label>Hasta<input required type="date" value={leave.end_date} onChange={(event) => setLeave({ ...leave, end_date: event.target.value })} /></label></div><label>Motivo<textarea required value={leave.reason} onChange={(event) => setLeave({ ...leave, reason: event.target.value })} /></label><button>Enviar solicitud</button></form><section className="role-panel enterprise-records"><h2>Mis solicitudes</h2>{selfService?.leave_requests.map((item) => <article key={item.id}><span><b>{item.leave_type}</b><small>{item.start_date} → {item.end_date} · {item.reason}</small></span><em>{item.status}</em></article>)}</section></div>}
    {tab === 'VOUCHERS' && <section className="technician-board employee-vouchers">{selfService?.vouchers.map((item) => <article key={item.id}><header><span><small>{item.number}</small><h2>{item.period_start} → {item.period_end}</h2></span><b>{item.status}</b></header><dl><div><dt>Bruto</dt><dd>L {Number(item.gross).toFixed(2)}</dd></div><div><dt>Deducciones</dt><dd>L {Number(item.deductions).toFixed(2)}</dd></div><div><dt>Neto</dt><dd>L {Number(item.net).toFixed(2)}</dd></div><div><dt>Aporte patronal</dt><dd>L {Number(item.employer_contributions).toFixed(2)}</dd></div></dl><button onClick={() => window.open(`/api/v1/staff/self-service/vouchers/${item.id}/html`, '_blank', 'noopener,noreferrer')}><BadgeDollarSign /> Imprimir voucher</button></article>)}{!selfService?.vouchers.length && <div className="empty-bookings">No hay vouchers aprobados para esta cuenta.</div>}</section>}
  </div>;
}
